# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.21.4/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.21.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wrz/share/myWebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wrz/share/myWebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.21.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.21.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wrz/share/myWebServer/CMakeFiles /home/wrz/share/myWebServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wrz/share/myWebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserver

# Build rule for target.
webserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserver
.PHONY : webserver

# fast build rule for target.
webserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/build
.PHONY : webserver/fast

version_0.3/src/deadlock_sucess.o: version_0.3/src/deadlock_sucess.cpp.o
.PHONY : version_0.3/src/deadlock_sucess.o

# target to build an object file
version_0.3/src/deadlock_sucess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/deadlock_sucess.cpp.o
.PHONY : version_0.3/src/deadlock_sucess.cpp.o

version_0.3/src/deadlock_sucess.i: version_0.3/src/deadlock_sucess.cpp.i
.PHONY : version_0.3/src/deadlock_sucess.i

# target to preprocess a source file
version_0.3/src/deadlock_sucess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/deadlock_sucess.cpp.i
.PHONY : version_0.3/src/deadlock_sucess.cpp.i

version_0.3/src/deadlock_sucess.s: version_0.3/src/deadlock_sucess.cpp.s
.PHONY : version_0.3/src/deadlock_sucess.s

# target to generate assembly for a file
version_0.3/src/deadlock_sucess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/deadlock_sucess.cpp.s
.PHONY : version_0.3/src/deadlock_sucess.cpp.s

version_0.3/src/export_fun.o: version_0.3/src/export_fun.cpp.o
.PHONY : version_0.3/src/export_fun.o

# target to build an object file
version_0.3/src/export_fun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/export_fun.cpp.o
.PHONY : version_0.3/src/export_fun.cpp.o

version_0.3/src/export_fun.i: version_0.3/src/export_fun.cpp.i
.PHONY : version_0.3/src/export_fun.i

# target to preprocess a source file
version_0.3/src/export_fun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/export_fun.cpp.i
.PHONY : version_0.3/src/export_fun.cpp.i

version_0.3/src/export_fun.s: version_0.3/src/export_fun.cpp.s
.PHONY : version_0.3/src/export_fun.s

# target to generate assembly for a file
version_0.3/src/export_fun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/export_fun.cpp.s
.PHONY : version_0.3/src/export_fun.cpp.s

version_0.3/src/main.o: version_0.3/src/main.cpp.o
.PHONY : version_0.3/src/main.o

# target to build an object file
version_0.3/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/main.cpp.o
.PHONY : version_0.3/src/main.cpp.o

version_0.3/src/main.i: version_0.3/src/main.cpp.i
.PHONY : version_0.3/src/main.i

# target to preprocess a source file
version_0.3/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/main.cpp.i
.PHONY : version_0.3/src/main.cpp.i

version_0.3/src/main.s: version_0.3/src/main.cpp.s
.PHONY : version_0.3/src/main.s

# target to generate assembly for a file
version_0.3/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/main.cpp.s
.PHONY : version_0.3/src/main.cpp.s

version_0.3/src/ntyreactor.o: version_0.3/src/ntyreactor.cpp.o
.PHONY : version_0.3/src/ntyreactor.o

# target to build an object file
version_0.3/src/ntyreactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/ntyreactor.cpp.o
.PHONY : version_0.3/src/ntyreactor.cpp.o

version_0.3/src/ntyreactor.i: version_0.3/src/ntyreactor.cpp.i
.PHONY : version_0.3/src/ntyreactor.i

# target to preprocess a source file
version_0.3/src/ntyreactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/ntyreactor.cpp.i
.PHONY : version_0.3/src/ntyreactor.cpp.i

version_0.3/src/ntyreactor.s: version_0.3/src/ntyreactor.cpp.s
.PHONY : version_0.3/src/ntyreactor.s

# target to generate assembly for a file
version_0.3/src/ntyreactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/ntyreactor.cpp.s
.PHONY : version_0.3/src/ntyreactor.cpp.s

version_0.3/src/thread_pool.o: version_0.3/src/thread_pool.cpp.o
.PHONY : version_0.3/src/thread_pool.o

# target to build an object file
version_0.3/src/thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/thread_pool.cpp.o
.PHONY : version_0.3/src/thread_pool.cpp.o

version_0.3/src/thread_pool.i: version_0.3/src/thread_pool.cpp.i
.PHONY : version_0.3/src/thread_pool.i

# target to preprocess a source file
version_0.3/src/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/thread_pool.cpp.i
.PHONY : version_0.3/src/thread_pool.cpp.i

version_0.3/src/thread_pool.s: version_0.3/src/thread_pool.cpp.s
.PHONY : version_0.3/src/thread_pool.s

# target to generate assembly for a file
version_0.3/src/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/version_0.3/src/thread_pool.cpp.s
.PHONY : version_0.3/src/thread_pool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserver"
	@echo "... version_0.3/src/deadlock_sucess.o"
	@echo "... version_0.3/src/deadlock_sucess.i"
	@echo "... version_0.3/src/deadlock_sucess.s"
	@echo "... version_0.3/src/export_fun.o"
	@echo "... version_0.3/src/export_fun.i"
	@echo "... version_0.3/src/export_fun.s"
	@echo "... version_0.3/src/main.o"
	@echo "... version_0.3/src/main.i"
	@echo "... version_0.3/src/main.s"
	@echo "... version_0.3/src/ntyreactor.o"
	@echo "... version_0.3/src/ntyreactor.i"
	@echo "... version_0.3/src/ntyreactor.s"
	@echo "... version_0.3/src/thread_pool.o"
	@echo "... version_0.3/src/thread_pool.i"
	@echo "... version_0.3/src/thread_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

